name: Wii build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install python
        run: |
          sudo apt update
          sudo apt install --yes python3

      - name: Compile Wii build
        run: |
          make
